config/routes.rb
Rails.application.routes.draw do
  resources :uploaded_logs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "uploaded_logs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :uploaded_log
  has_many :kill_by_means, dependent: :destroy
  has_many :players, dependent: :destroy
end

app/models/kill_by_mean.rb
class KillByMean < ApplicationRecord
  belongs_to :game
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
end

app/models/player_ranking.rb
class PlayerRanking < ApplicationRecord
  belongs_to :uploaded_log
end

app/models/uploaded_log.rb
class UploadedLog < ApplicationRecord
  has_one_attached :logfile
  has_many :games, dependent: :destroy
  has_many :player_rankings, dependent: :destroy

  after_create_commit -> { ProcessUploadedLogJob.perform_later(self) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/uploaded_logs_controller.rb
class UploadedLogsController < ApplicationController
  before_action :set_uploaded_log, only: %i[show destroy]

  # GET /uploaded_logs or /uploaded_logs.json
  def index
    @uploaded_logs = UploadedLog.all
  end

  # GET /uploaded_logs/1 or /uploaded_logs/1.json
  def show; end

  # GET /uploaded_logs/new
  def new
    @uploaded_log = UploadedLog.new
  end

  # POST /uploaded_logs or /uploaded_logs.json
  def create
    @uploaded_log = UploadedLog.create(uploaded_log_params)

    respond_to do |format|
      format.turbo_stream
    end
  end

  # DELETE /uploaded_logs/1 or /uploaded_logs/1.json
  def destroy
    @uploaded_log.destroy!

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_uploaded_log
    @uploaded_log = UploadedLog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def uploaded_log_params
    params.require(:uploaded_log).permit(:logfile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploaded_logs_helper.rb
module UploadedLogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloudwalkTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link  rel="stylesheet"  href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploaded_logs/_base_report.html.erb
<%= turbo_frame_tag 'content' do %>
  <div class="report">
    <div class="rankings">
      <strong>Player Ranking</strong>
      <ol>
        <% @uploaded_log.player_rankings.each do |player| %>
          <li><%= player.player %></li>
        <% end %>
      </ol>
    </div>
    <div class="games">
      <% @uploaded_log.games.each_with_index do |game, idx| %>
        <div class="game">
          <div class="game-details">
            <strong>Game <%= idx + 1 %></strong>
            <p>Total Kills: <%= game.total_kills %></p>
            <p>Player Names: <%= game.player_names %></p>
          </div>
          <div class="player-kills">
            <strong>Player Kills</strong>
            <ul>
              <% game.players.each do |player| %>
                <li><%= player.name %> -&gt; <%= player.kill_count%> kill points</li>
              <% end %>
            </ul>
          </div>
          <div class="kill-by-means">
            <strong>Kill by means</strong>
            <ul>
              <% game.kill_by_means.each do |kill| %>
                <li><%= kill.mean %> -&gt; <%= kill.kill_count%> kills</li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <div class="buttons">
      <%= link_to "Destroy this uploaded log", @uploaded_log, data: {turbo_stream: true, "turbo-method": :delete} %>
    </div>
  </div>
<% end %>

app/views/uploaded_logs/_form.html.erb
<%= form_with(model: uploaded_log, data: {turbo_stream: true}) do |form| %>
  <% if uploaded_log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(uploaded_log.errors.count, "error") %> prohibited this uploaded_log from being saved:</h2>

      <ul>
        <% uploaded_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :logfile, style: "display: block" %>
    <%= form.file_field :logfile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uploaded_logs/_notice.html.erb
<%= turbo_frame_tag 'content' do %>
  <div class="notice"><%= notice%></div>
<%end%>

app/views/uploaded_logs/_uploaded_log.html.erb
<div id="uploaded_<%= dom_id uploaded_log %>">
  <p>
    <strong>View File:</strong>
    <%= link_to uploaded_log.logfile.filename, uploaded_log.logfile if uploaded_log.logfile.attached? %>
  </p>
  <p>
    <%= link_to 'View Report', uploaded_log, data: {turbo_frame: 'content'}%>
  </p>
</div>

app/views/uploaded_logs/create.turbo_stream.erb
<%= turbo_stream.prepend 'list', partial: 'uploaded_log', locals: { uploaded_log: @uploaded_log } %>
<%= turbo_stream.replace 'content', partial: 'notice', locals: { notice: 'Uploaded log was successfully created.' }%>

app/views/uploaded_logs/destroy.turbo_stream.erb
<%= turbo_stream.remove "uploaded_uploaded_log_#{@uploaded_log.id}" %>
<%= turbo_stream.replace 'content', partial: 'notice', locals: { notice: 'Log file removed.' }%>

app/views/uploaded_logs/index.html.erb
<header>
  <h1>Uploaded logs</h1>
</header>
<div class="my-grid">
  <div class='list' id="uploaded_logs">
    <%= turbo_stream_from 'list_updates' %>
    <%= turbo_frame_tag 'list' do %>
      <% @uploaded_logs.each do |uploaded_log| %>
        <%= render uploaded_log %>
      <% end %>
    <% end %>
    <%= link_to "New uploaded log", new_uploaded_log_path, data: {turbo_frame: 'content'} %>
  </div>
  <div class="content">
    <%= turbo_frame_tag 'content'%>
  </div>
</div>

app/views/uploaded_logs/new.html.erb
<%= turbo_frame_tag 'content' do %>
  <h1>New uploaded log</h1>
  <%= render "form", uploaded_log: @uploaded_log %>
<% end %>
<br>
<div>
  <%= link_to "Back to uploaded logs", uploaded_logs_path %>
</div>

app/views/uploaded_logs/show.html.erb
<%= render 'base_report' %>